version: '3'

services:
  envoy:
    build:
      context: .
      dockerfile: Dockerfile.envoy
    ports:
      - '8080:8080'
      - '9901:9901'
    networks:
      - server-net
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '9090:9090'
    networks:
      - server-net

networks:
  server-net: